apiVersion: v1
data:
  KAFKA_BROKERS: kafka-3239ff2a-odesssey-bank.c.aivencloud.com:23611
  KAFKA_SECURITY_PROTOCOL: SSL
  KAFKA_SSL_CA_LOCATION: /etc/kafka-ssl/ca.cert
  KAFKA_SSL_CERTIFICATE_LOCATION: /etc/kafka-ssl/access.cert
  KAFKA_SSL_KEYSTORE_TYPE: PEM
  KAFKA_SSL_KEY_LOCATION: /etc/kafka-ssl/access.key
  KAFKA_SSL_TRUSTSTORE_TYPE: PEM
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: 'true'
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: 'true'
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: 'true'
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  SPRING_FLYWAY_VALIDATEONMIGRATE: 'false'
  SPRING_KAFKA_ADMIN_AUTO_CREATE: 'false'
  SPRING_PROFILES_ACTIVE: k8s
  SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
  ZIPKIN_URL: http://zipkin:9411
kind: ConfigMap
metadata:
  name: aml-service-config
  namespace: banking
