# Aiven managed Kafka — external service endpoint
# No in-cluster Kafka needed; SSL certs stored in aiven-kafka-ssl secret
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: banking
spec:
  type: ExternalName
  externalName: kafka-3239ff2a-odesssey-bank.c.aivencloud.com
  ports:
    - port: 23611
      targetPort: 23611
