apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-service-config
  namespace: banking
data:
  KAFKA_BROKERS: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ZIPKIN_URL: http://zipkin:9411
  SPRING_PROFILES_ACTIVE: k8s
