apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service
  namespace: banking
  labels:
    app: iam-service
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-service
  template:
    metadata:
      labels:
        app: iam-service
    spec:
      containers:
        - name: iam-service
          # CD pipeline updates this tag on every merge to main
          image: ghcr.io/odyssey-lab-v0/iam-service:a41d452
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: banking-db-secret
            - secretRef:
                name: banking-jwt-secret
            - configMapRef:
                name: iam-service-config
            - secretRef:
                name: aiven-kafka-spring-ssl
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 15
          volumeMounts:
            - name: kafka-ssl
              mountPath: /etc/kafka-ssl
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: kafka-ssl
          secret:
            secretName: aiven-kafka-ssl
