apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: banking
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/odyssey-lab-v0/notification-service:94ff037
          ports:
            - containerPort: 8086
          envFrom:
            - secretRef:
                name: banking-db-secret
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: aiven-kafka-spring-ssl
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            periodSeconds: 15
          volumeMounts:
            - name: kafka-ssl
              mountPath: /etc/kafka-ssl
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: kafka-ssl
          secret:
            secretName: aiven-kafka-ssl
