apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: banking
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
