apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Odyssey-Lab-V0/odyssey-bank.git
    targetRevision: main
    path: k8s/services
    directory:
      recurse: true    # picks up all subdirs (iam-service/, onboarding-service/, etc.)
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
